-- MySQL Script generated by MySQL Workbench
-- Thu Mar  1 12:37:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Geslacht_Virus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Geslacht_Virus` (
  `Geslacht` VARCHAR(45) NOT NULL,
  `Geslacht_ID` INT NOT NULL,
  PRIMARY KEY (`Geslacht_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Familie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Familie` (
  `Virus_Familie` VARCHAR(45) NOT NULL,
  `ID_Familie` INT NOT NULL,
  `Geslacht_Virus_Geslacht_ID` INT NOT NULL,
  PRIMARY KEY (`ID_Familie`, `Geslacht_Virus_Geslacht_ID`),
  INDEX `fk_Familie_Geslacht_Virus1_idx` (`Geslacht_Virus_Geslacht_ID` ASC),
  CONSTRAINT `fk_Familie_Geslacht_Virus1`
    FOREIGN KEY (`Geslacht_Virus_Geslacht_ID`)
    REFERENCES `mydb`.`Geslacht_Virus` (`Geslacht_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Virus_Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Virus_Info` (
  `idVirus_Info` INT NOT NULL AUTO_INCREMENT,
  `Virus_Name` VARCHAR(45) NOT NULL,
  `Virus_Seq` LONGTEXT NOT NULL,
  `Virus_Prot_Name` VARCHAR(45) NOT NULL,
  `Virus_Prot_Seq` LONGTEXT NOT NULL,
  `Familie_ID_Familie` INT NOT NULL,
  PRIMARY KEY (`idVirus_Info`, `Familie_ID_Familie`),
  UNIQUE INDEX `idVirus_Info_UNIQUE` (`idVirus_Info` ASC),
  INDEX `fk_Virus_Info_Familie1_idx` (`Familie_ID_Familie` ASC),
  CONSTRAINT `fk_Virus_Info_Familie1`
    FOREIGN KEY (`Familie_ID_Familie`)
    REFERENCES `mydb`.`Familie` (`ID_Familie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Functie_Eiwit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Functie_Eiwit` (
  `idFuncties_Eiwit` INT NOT NULL,
  `Functies_Eiwitcol` VARCHAR(45) NOT NULL,
  `Virus_Info_idVirus_Info` INT NOT NULL,
  `Virus_Info_Familie_ID_Familie` INT NOT NULL,
  PRIMARY KEY (`idFuncties_Eiwit`, `Virus_Info_idVirus_Info`, `Virus_Info_Familie_ID_Familie`),
  INDEX `fk_Functie_Eiwit_Virus_Info1_idx` (`Virus_Info_idVirus_Info` ASC, `Virus_Info_Familie_ID_Familie` ASC),
  CONSTRAINT `fk_Functie_Eiwit_Virus_Info1`
    FOREIGN KEY (`Virus_Info_idVirus_Info` , `Virus_Info_Familie_ID_Familie`)
    REFERENCES `mydb`.`Virus_Info` (`idVirus_Info` , `Familie_ID_Familie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hostnames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hostnames` (
  `idHostnames` INT NOT NULL,
  `Hostname` VARCHAR(45) NOT NULL,
  `Virus_Info_idVirus_Info` INT NOT NULL,
  `Virus_Info_Familie_ID_Familie` INT NOT NULL,
  PRIMARY KEY (`idHostnames`, `Virus_Info_idVirus_Info`, `Virus_Info_Familie_ID_Familie`),
  INDEX `fk_Hostnames_Virus_Info1_idx` (`Virus_Info_idVirus_Info` ASC, `Virus_Info_Familie_ID_Familie` ASC),
  CONSTRAINT `fk_Hostnames_Virus_Info1`
    FOREIGN KEY (`Virus_Info_idVirus_Info` , `Virus_Info_Familie_ID_Familie`)
    REFERENCES `mydb`.`Virus_Info` (`idVirus_Info` , `Familie_ID_Familie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Virus_Classificatie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Virus_Classificatie` (
  `idClass` INT NOT NULL,
  `Virus_Class` VARCHAR(45) NOT NULL,
  `Virus_Info_idVirus_Info` INT NOT NULL,
  `Virus_Info_Familie_ID_Familie` INT NOT NULL,
  PRIMARY KEY (`idClass`, `Virus_Info_idVirus_Info`, `Virus_Info_Familie_ID_Familie`),
  INDEX `fk_Virus_Classificatie_Virus_Info1_idx` (`Virus_Info_idVirus_Info` ASC, `Virus_Info_Familie_ID_Familie` ASC),
  CONSTRAINT `fk_Virus_Classificatie_Virus_Info1`
    FOREIGN KEY (`Virus_Info_idVirus_Info` , `Virus_Info_Familie_ID_Familie`)
    REFERENCES `mydb`.`Virus_Info` (`idVirus_Info` , `Familie_ID_Familie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
